name: build
on:
  push:
  pull_request:

env:
  GO_VERSION: stable

jobs:

  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
          cache-dependency-path: go.sum
          check-latest: false

      - name: go build
        run: |
          go build ./...
        env:
          GOPATH: /home/runner/work/${{ github.event.repository.name }}/go